name: GitHub release

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt -y update && sudo apt -y install docker-compose

      - name: Docker build
        run: docker-compose build github-release

      - name: Export app
        run: docker run -v $(pwd)/dist:/dist github-release cp -rfv ./platforms/android/app/build/outputs/apk/debug/app-debug.apk /dist 

      - name: Gradle path
        run: docker run -v $(pwd)/dist:/dist github-release which gradle

      - name: Create release
        run: gh release create v$( date +%Y%m%d%H%M ) ./dist/app-debug.apk 
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

